/* ==========================================
   pdf.js
   Fortune Performance Indicator
   Requires:
   https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js
========================================== */

/* ==========================================
   BUILD REPORT DATA
========================================== */

function getReportData() {

    const result = calculateFPI();

    return {

        candidate:
            document.getElementById("candidateName")?.value || "",

        batch:
            document.getElementById("batch")?.value || "",

        week:
            document.getElementById("week")?.value || "",

        mentor:
            document.getElementById("mentor")?.value || "",

        learning: result.learning,

        reinforcement: result.reinforcement,

        performance: result.performance,

        learningPercent:
            result.learningPercent.toFixed(1),

        reinforcementPercent:
            result.reinforcementPercent.toFixed(1),

        performancePercent:
            result.performancePercent.toFixed(1),

        fpi:
            result.fpi.toFixed(1),

        status:
            result.status.text

    };

}

/* ==========================================
   BUILD PDF CONTENT
========================================== */

function buildReportHTML() {

    const data = getReportData();

    return `

    <div style="
        padding:40px;
        font-family:Arial,sans-serif;
        color:#222;
    ">

        <h1 style="
            text-align:center;
            color:#2563eb;
        ">
            Fortune Performance Indicator
        </h1>

        <hr>

        <h2>Candidate Details</h2>

        <table style="width:100%;border-collapse:collapse;">

            <tr>
                <td><strong>Name</strong></td>
                <td>${data.candidate}</td>
            </tr>

            <tr>
                <td><strong>Batch</strong></td>
                <td>${data.batch}</td>
            </tr>

            <tr>
                <td><strong>Week</strong></td>
                <td>${data.week}</td>
            </tr>

            <tr>
                <td><strong>Mentor</strong></td>
                <td>${data.mentor}</td>
            </tr>

        </table>

        <br>

        <h2>Weekly Scores</h2>

        <table
            border="1"
            cellpadding="8"
            cellspacing="0"
            width="100%"
            style="border-collapse:collapse;">

            <thead>

                <tr>

                    <th>Index</th>

                    <th>Score</th>

                    <th>Percentage</th>

                </tr>

            </thead>

            <tbody>

                <tr>

                    <td>Learning</td>

                    <td>${data.learning} / 210</td>

                    <td>${data.learningPercent}%</td>

                </tr>

                <tr>

                    <td>Reinforcement</td>

                    <td>${data.reinforcement} / 168</td>

                    <td>${data.reinforcementPercent}%</td>

                </tr>

                <tr>

                    <td>Performance</td>

                    <td>${data.performance} / 105</td>

                    <td>${data.performancePercent}%</td>

                </tr>

            </tbody>

        </table>

        <br>

        <h2>
            Overall FPI :
            ${data.fpi}%
        </h2>

        <h2>
            Status :
            ${data.status}
        </h2>

        <br><br>

        <p style="text-align:center;font-size:13px;">

            Generated by

            <strong>

                Fortune Performance Indicator

            </strong>

        </p>

    </div>

    `;

}

/* ==========================================
   DOWNLOAD PDF
========================================== */

function downloadPDF() {

    if (typeof html2pdf === "undefined") {

        alert(

            "html2pdf.js is not loaded."

        );

        return;

    }

    showLoading();

    const container = document.createElement("div");

    container.innerHTML = buildReportHTML();

    const candidate =
        document.getElementById("candidateName")?.value || "Candidate";

    const week =
        document.getElementById("week")?.value || "Week";

    const options = {

        margin: 10,

        filename:
            `${candidate}_FPI_${week}.pdf`,

        image: {

            type: "jpeg",

            quality: 1

        },

        html2canvas: {

            scale: 2,

            useCORS: true

        },

        jsPDF: {

            unit: "mm",

            format: "a4",

            orientation: "portrait"

        }

    };

    html2pdf()

        .set(options)

        .from(container)

        .save()

        .then(() => {

            hideLoading();

        })

        .catch(error => {

            hideLoading();

            console.error(error);

            alert("Unable to generate PDF.");

        });

}

/* ==========================================
   BUTTON BINDING
========================================== */

function initializePDF() {

    const button =
        document.getElementById("downloadBtn");

    if (!button) return;

    button.addEventListener(

        "click",

        downloadPDF

    );

}